# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1d91a62e201dba21e6f7125f28ccef5ea77648d7e67c90523d38aeabd27208b48ef15ea009b6b1e2165615f4f080b54a73620bc89a19bc7247241ed3a5d058d

test:
  secret_key_base: 78bf359f3ba95a112d291e7ad1787271b159df1e7b54d5890e197d5b16f885c12e680aaffb82763374b39bdae3ae65f3c0b1e3bec4cf3bd693649d1ccfa71e94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
